### ISSUE TITLE
Unable to load DLL 'Shcore.dll' in MyScript iink editor

### ISSUE THREAD

**Issue by Henry-YSLin** [Profound-Education-Centre/DeltaQuestionEditor-WPF#15]
From Windows 7 virtual machine

Happens when creating a new set (when the math editor control is loaded)

**Stack trace (Auto-filled)**

```
Exception in DeltaQuestionEditor-WPF v1.5.0.0
Source: MyScript.InteractiveInk.UIReferenceImplementation.Wpf
Unable to load DLL 'Shcore.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at MyScript.IInk.UIReferenceImplementation.DisplayResolution.GetDpiForMonitor(IntPtr hmonitor, Int32 dpiType, UInt32& dpiX, UInt32& dpiY)
   at MyScript.IInk.UIReferenceImplementation.DisplayResolution.GetDpi(IntPtr hwnd, Boolean rawDPI, UInt32& dpiX, UInt32& dpiY)
   at MyScript.IInk.UIReferenceImplementation.DisplayResolution.GetDpi(Window window, Boolean rawDPI)
   at MyScript.IInk.UIReferenceImplementation.EditorUserControl.Initialize(Window window)
   at DeltaQuestionEditor_WPF.Views.ContentEditor.<UserControl_Loaded>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Henry-YSLin** [comment]
Fixed in c0c2d5aa429c5683e6b15ad3e3397e8cd088c452
